### PR TITLE
Use snowflake transport in Lyrebird

### PR DESCRIPTION
**Pull request by cohosh**
Removes the need for our own snowflakeClientFactory.

### CODE REVIEW

**Comment by syphyr** [comment]
Lyrebird only contains the client for snowflake. Orbot needs the snowflake client and the snowflake server which was provided before.

**Comment by cohosh** [comment]
> Lyrebird only contains the client for snowflake. Orbot needs the snowflake client and the snowflake server which was provided before.

Orbot did not run any part of the Snowflake server. Do you mean the proxy? If so, this refactor still includes proxy support, just not in this specific commit. Take a look at https://github.com/cohosh/IPtProxy/pull/1 for the full refactor.

**Comment by syphyr** [comment]
I was thinking about kindness mode, but it looks like that is still supported.

**Comment by tladesignz** [comment]
Thank you, @cohosh!
Just so you know: You changed MaxPeers to stringly typed, probably, because then there's no conversion necessary later. I'll revert that later, because from the perspective of the user of the API, this looks like a bad idea.

**Comment by cohosh** [comment]
> Thank you, @cohosh! Just so you know: You changed MaxPeers to stringly typed, probably, because then there's no conversion necessary later. I'll revert that later, because from the perspective of the user of the API, this looks like a bad idea.

Okay, makes sense. Converting that int to a string for inclusion in `pt.Args` isn't difficult at all, and keeping it an int for API users sounds like the right call.

**Pull request merged**
