### PR TITLE
Refactor IPtProxy to remove dependency on patch files

### PR DESCRIPTION
**Pull request by cohosh**
I approached this as more of a rewrite than a refactor, because I wanted to allow us to fully explore the API design space. That said, if you want to stick to the old API exactly, that is certainly doable. This is simply how I would approach it if I were writing it from scratch. I am very interested in your feedback, I think we should iterate on what an ideal API would be.

## Major Changes

A lot of the goptlib function calls that were present in the old version, particularly in the patched files are unnecessary here. Since pluggable transport processes are not spawned by the Tor process, there is no need for setting the environment variables, or for sending the stdout messages such as [`pt.Cmethod`](https://pkg.go.dev/git.torproject.org/pluggable-transports/goptlib.git#Cmethod). There is no parent process around to read these messages. Cutting out these unnecessary pieces helped reduce the total lines of code.

I also reworked the way that ports are chosen for each of the transport listeners. It's easier to let the OS choose the port by calling
```golang
ln, err : = pt.ListenSocks("tcp", "127.0.0.1:0")
```
and then later retrieving that port with
```golang
int(ln.Addr().(*net.TCPAddr).AddrPort().Port())
```
rather than adding in extra logic to iterate through potential ports until an unused one is found. Perhaps this is a misunderstanding on my part. Do you require a restricted port range?

## API changes

The largest change in the API isn't strictly speaking necessary, but might be easier to manage by reducing the reliance on global variables.

```golang
package IPtProxy // import "github.com/tladesignz/IPtProxy.git"


FUNCTIONS

func LyrebirdVersion() string
func SnowflakeVersion() string

TYPES

type IPtProxy struct {
	EnableLogging bool
	UnsafeLogging bool
	LogLevel      string
	StateDir      string

	// SnowflakeIceServers is a comma-separated list of ICE server addresses
	SnowflakeIceServers string
	SnowflakeBrokerUrl  string
	// SnowflakeFrontDomains is a comma-separated list of domains for either
	// the domain fronting or AMP cache rendezvous methods
	SnowflakeFrontDomains string
	SnowflakeAmpCacheUrl  string
	SnowflakeSqsUrl       string
	SnowflakeSqsCreds     string

	// Has unexported fields.
}

func NewIPtProxy(stateDir string) *IPtProxy
func (p *IPtProxy) GetLocalAddress(methodName string) string
func (p *IPtProxy) GetPort(methodName string) int
func (p *IPtProxy) Init()
func (p *IPtProxy) Start(methodName string, proxy string)
func (p *IPtProxy) Stop(methodName string)

type SnowflakeProxy struct {
	Capacity    int
	BrokerUrl   string
	RelayUrl    string
	StunServer  string
	NatProbeUrl string

	// Has unexported fields.
}

func (sp *SnowflakeProxy) IsRunning() bool
func (sp *SnowflakeProxy) Start()
func (sp *SnowflakeProxy) Stop()
```

Another major change is to use a struct with exported fields (modifiable in java through the use of generated getters and setters), rather than large functions signatures. My thought is that this will be easier to maintain and provide backwards compatibility in the event of upstream changes and new functionality. A typical use in java would be:

```java
 import IPtProxy.IPtProxy;

// ...

 // Create a new IPtProxy instance with provided state directory
 iptproxy = IPtProxy.newIPtProxy("/path/to/statedir");
 iptproxy.init();

 // Start listening for obfs4 and meek connections, using an outgoing proxy
 iptproxy.start("obfs4", "socks5://localhost:8001");
 iptproxy.start("meek_lite", "socks5://localhost:8001");

 // Get the address that is listening for SOCKS connections for each transport
 obfs4Addr = iptproxy.getLocalAddress("obfs4");
 meekAddr = iptproxy.getLocalAddress("meek_lite");
 
// Or, alternatively, get the port
obfs4Port = iptproxy.getPort("obfs4");

 // Start listening for snowflake connections
 // Note that snowflake setup can happen either here or with SOCKS arguments on
 // a per-connection basis.
 iptproxy.setSnowflakeIceServers("stun:stun.l.google.com:19302,stun:stun.l.google.com:5349");
 iptproxy.start("snowflake", "");
    
 // Stop transports
 iptproxy.stop("snowflake");
 iptproxy.stop("obfs4"); 
 iptproxy.stop("meek_lite");
```

I started updated orbot to use this new version of IPtProxy:
<details>
<summary> Orbot patch </summary>

```diff
index de00e9c9..e2543587 100644
--- a/app/src/main/java/org/torproject/android/ConfigConnectionBottomSheet.kt
+++ b/app/src/main/java/org/torproject/android/ConfigConnectionBottomSheet.kt
@@ -1,6 +1,7 @@
 package org.torproject.android
 
 import IPtProxy.IPtProxy
+import IPtProxy.IPtProxy_
 import android.content.Context
 import android.os.Bundle
 import android.telephony.TelephonyManager
@@ -38,6 +39,8 @@ class ConfigConnectionBottomSheet() :
     private lateinit var btnAction: Button
     private lateinit var btnAskTor: Button
 
+    private lateinit var iptproxy: IPtProxy_
+
     companion object {
         public fun newInstance(callbacks: ConnectionHelperCallbacks): ConfigConnectionBottomSheet {
             return ConfigConnectionBottomSheet().apply {
@@ -201,8 +204,9 @@ class ConfigConnectionBottomSheet() :
             fileCacheDir.mkdir()
         }
 
-        IPtProxy.setStateLocation(fileCacheDir.absolutePath)
-        IPtProxy.startLyrebird("DEBUG", false, false, null)
+        this.iptproxy = IPtProxy.newIPtProxy(fileCacheDir.absolutePath)
+        this.iptproxy.init()
+        this.iptproxy.start("moat_lite", "")
         val pUsername =
             "url=" + OrbotService.getCdnFront("moat-url") + ";front=" + OrbotService.getCdnFront("moat-
front")
         val pPassword = "\u0000"
@@ -237,7 +241,7 @@ class ConfigConnectionBottomSheet() :
                     setPreferenceForSmartConnect()
                 }
 
-                IPtProxy.stopLyrebird()
+                this.iptproxy.stop("moat")
             }
         }, {
             // TODO what happens to the app in this case?!
diff --git a/app/src/main/java/org/torproject/android/MoatBottomSheet.kt b/app/src/main/java/org/torproj
ect/android/MoatBottomSheet.kt
index 8fcef516..899aae03 100644
--- a/app/src/main/java/org/torproject/android/MoatBottomSheet.kt
+++ b/app/src/main/java/org/torproject/android/MoatBottomSheet.kt
@@ -1,6 +1,7 @@
 package org.torproject.android
 
 import IPtProxy.IPtProxy
+import IPtProxy.IPtProxy_
 import android.app.Activity
 import android.graphics.BitmapFactory
 import android.os.Bundle
@@ -64,6 +65,8 @@ class MoatBottomSheet(private val callbacks: ConnectionHelperCallbacks) :
     private lateinit var ivCaptcha: ImageView
     private lateinit var mQueue: RequestQueue
     private lateinit var mBtnAction: Button
+    private var mIPtProxy: IPtProxy_ = IPtProxy.newIPtProxy("")
+
 
     private fun setupMoat() {
         val fileCacheDir = File(requireActivity().cacheDir, "pt")
@@ -71,13 +74,14 @@ class MoatBottomSheet(private val callbacks: ConnectionHelperCallbacks) :
             fileCacheDir.mkdir()
         }
 
-        IPtProxy.setStateLocation(fileCacheDir.absolutePath)
+        this.mIPtProxy.stateDir =  fileCacheDir.absolutePath
+        this.mIPtProxy.init()
 
-        IPtProxy.startLyrebird("DEBUG", false, false, null)
+        this.mIPtProxy.start("meek_lite", "")
 
         val phs = ProxiedHurlStack(
             "127.0.0.1",
-            IPtProxy.meekPort().toInt(),
+            mIPtProxy.getPort("meek_lite").toInt(),
             "url=" + OrbotService.getCdnFront("moat-url") + ";front=" + OrbotService.getCdnFront("moat-front"),
             "\u0000"
         )
diff --git a/orbotservice/src/main/java/org/torproject/android/service/OrbotService.java b/orbotservice/src/main/java/org/torproject/android/service/OrbotService.java
index a68716b6..a73278fd 100644
--- a/orbotservice/src/main/java/org/torproject/android/service/OrbotService.java
+++ b/orbotservice/src/main/java/org/torproject/android/service/OrbotService.java
@@ -70,6 +70,8 @@ import java.util.concurrent.ExecutorService;
 import java.util.concurrent.Executors;
 
 import IPtProxy.IPtProxy;
+import IPtProxy.IPtProxy_;
+import IPtProxy.SnowflakeProxy;
 
 import androidx.annotation.NonNull;
 import androidx.annotation.RequiresApi;
@@ -116,6 +118,9 @@ public class OrbotService extends VpnService implements OrbotConstants {
     private boolean mHasPower = false;
     private boolean mHasWifi = false;
 
+    private IPtProxy_ iptproxy;
+    private SnowflakeProxy sfproxy;
+
     /**
      * @param bridgeList bridges that were manually entered into Orbot settings
      * @return Array with each bridge as an element, no whitespace entries see issue #289...
@@ -278,9 +283,9 @@ public class OrbotService extends VpnService implements OrbotConstants {
         // todo this needs to handle a lot of different cases that haven't been defined yet
         // todo particularly this is true for the smart connection case...
         if (connectionPathway.startsWith(Prefs.PATHWAY_SNOWFLAKE) || Prefs.getPrefSmartTrySnowflake()) {
-            IPtProxy.stopSnowflake();
+            this.iptproxy.stop("snowflake");
         } else if (connectionPathway.equals(Prefs.PATHWAY_CUSTOM) || Prefs.getPrefSmartTryObfs4() != null) {
-            IPtProxy.stopLyrebird();
+            this.iptproxy.stop("snowflake");
         }
 
         stopTor();
@@ -368,7 +373,7 @@ public class OrbotService extends VpnService implements OrbotConstants {
         // @param maxPeers Capacity for number of multiplexed WebRTC peers. DEFAULTs to 1 if less than that.
         // @return Port number where Snowflake will listen on, if no error happens during start up.
          */
-        IPtProxy.startSnowflake(stunServer, target, front, null, null, null, null,true, false, false, 1);
+        this.iptproxy.start("snowflake", "");
 
     }
 
@@ -377,13 +382,21 @@ public class OrbotService extends VpnService implements OrbotConstants {
         var target = getCdnFront("snowflake-target-direct");
         var front = getCdnFront("snowflake-amp-front");
         var ampCache = getCdnFront("snowflake-amp-cache");
-        IPtProxy.startSnowflake(stunServers, target, front, ampCache, null, null, null, true, false, false, 1);
+        this.iptproxy.setSnowflakeIceServers(stunServers);
+        this.iptproxy.setSnowflakeBrokerUrl(target);
+        this.iptproxy.setSnowflakeFrontDomains(front);
+        this.iptproxy.setSnowflakeAmpCacheUrl(ampCache);
+        this.iptproxy.start("snowflake", "");
+    }
+
+    private void startLyrebird() {
+        this.iptproxy.start("obfs4", "");
     }
 
     private final SecureRandom mSecureRandGen = new SecureRandom(); //used to randomly select STUN servers for snowflake
 
     public synchronized void enableSnowflakeProxy() { // This is to host a snowflake entrance node / bridge
-        if (!IPtProxy.isSnowflakeProxyRunning()) {
+        if (this.iptproxy.getPort("snowflake") == 0) {
 
             if (Prefs.limitSnowflakeProxyingWifi() && (!mHasWifi))
                 return;
@@ -391,22 +404,16 @@ public class OrbotService extends VpnService implements OrbotConstants {
             if (Prefs.limitSnowflakeProxyingCharging() && (!mHasPower))
                 return;
 
-            var capacity = 1;
-            var keepLocalAddresses = false;
-            var unsafeLogging = false;
-            var stunServers = getCdnFront("snowflake-stun").split(",");
-
-            int randomIndex = mSecureRandGen.nextInt(stunServers.length);
-            var stunUrl = stunServers[randomIndex];
-            var relayUrl = getCdnFront("snowflake-relay-url");
-            var natProbeUrl = getCdnFront("snowflake-nat-probe");
-            var brokerUrl = getCdnFront("snowflake-target-direct");
-            IPtProxy.startSnowflakeProxy(capacity, brokerUrl, relayUrl, stunUrl, natProbeUrl, null, keepLocalAddresses, unsafeLogging, () -> {
-                Prefs.addSnowflakeServed();
-                if (!Prefs.showSnowflakeProxyMessage()) return;
-                var message = String.format(getString(R.string.snowflake_proxy_client_connected_msg), ONION_EMOJI, ONION_EMOJI);
-                new Handler(getMainLooper()).post(() -> Toast.makeText(getApplicationContext(), message, Toast.LENGTH_LONG).show());
-            });
+            if (this.sfproxy == null) {
+                this.sfproxy.setCapacity(1);
+                var stunServers = getCdnFront("snowflake-stun").split(",");
+                int randomIndex = mSecureRandGen.nextInt(stunServers.length);
+                this.sfproxy.setStunServer(stunServers[randomIndex]);
+                this.sfproxy.setRelayUrl("snowflake-relay-url");
+                this.sfproxy.setNatProbeUrl("snowflake-nat-probe");
+                this.sfproxy.setBrokerUrl("snowflake-target-direct");
+            }
+            this.sfproxy.start();
             logNotice(getString(R.string.log_notice_snowflake_proxy_enabled));
 
             if (Prefs.showSnowflakeProxyMessage()) {
@@ -475,8 +482,8 @@ public class OrbotService extends VpnService implements OrbotConstants {
     }
 
     public synchronized void disableSnowflakeProxy() {
-        if (IPtProxy.isSnowflakeProxyRunning()) {
-            IPtProxy.stopSnowflakeProxy();
+
+            this.iptproxy.stop("snowflake");
             logNotice(getString(R.string.log_notice_snowflake_proxy_disabled));
 
             if (Prefs.showSnowflakeProxyMessage()) {
@@ -484,7 +491,7 @@ public class OrbotService extends VpnService implements OrbotConstants {
                 new Handler(getMainLooper()).post(() -> Toast.makeText(getApplicationContext(), message, Toast.LENGTH_LONG).show());
             }
 
-        }
+
     }
 
     // if someone stops during startup, we may have to wait for the conn port to be setup, so we can properly shutdown tor
@@ -622,8 +629,8 @@ public class OrbotService extends VpnService implements OrbotConstants {
             fileCacheDir.mkdir();
 
         try {
-            IPtProxy.setStateLocation(fileCacheDir.getAbsolutePath());
-            debug("IPtProxy state: " + IPtProxy.getStateLocation());
+            this.iptproxy = IPtProxy.newIPtProxy(fileCacheDir.getAbsolutePath());
+            this.iptproxy.init();
         } catch (Error e) {
             debug("IPtProxy state: not installed; " + e.getLocalizedMessage());
 
@@ -1208,7 +1215,7 @@ public class OrbotService extends VpnService implements OrbotConstants {
 
     private StringBuffer processSettingsImplSnowflake(StringBuffer extraLines) {
         Log.d(TAG, "in snowflake torrc config");
-        extraLines.append("ClientTransportPlugin snowflake socks5 127.0.0.1:" + IPtProxy.snowflakePort()).append('\n');
+        extraLines.append("ClientTransportPlugin snowflake socks5 127.0.0.1:" + this.iptproxy.getPort("snowflake")).append('\n');
         for (String bridge : mSnowflakeBridges) {
             extraLines.append("Bridge ").append(bridge).append("\n");
         }
@@ -1217,7 +1224,7 @@ public class OrbotService extends VpnService implements OrbotConstants {
 
     private StringBuffer processSettingsImplObfs4(StringBuffer extraLines) {
         Log.d(TAG, "in obfs4 torrc config");
-        extraLines.append("ClientTransportPlugin obfs4 socks5 127.0.0.1:" + IPtProxy.obfs4Port()).append('\n');
+        extraLines.append("ClientTransportPlugin obfs4 socks5 127.0.0.1:" + this.iptproxy.getPort("obfs4")).append('\n');
         var bridgeList = "";
         if (Prefs.getConnectionPathway().equals(Prefs.PATHWAY_CUSTOM)) {
             bridgeList = Prefs.getBridgesList();
@@ -1468,7 +1475,7 @@ public class OrbotService extends VpnService implements OrbotConstants {
                     } else if (connectionPathway.equals(Prefs.PATHWAY_SNOWFLAKE_AMP)) {
                         startSnowflakeClientAmpRendezvous();
                     } else if (connectionPathway.equals(Prefs.PATHWAY_CUSTOM) || Prefs.getPrefSmartTryObfs4() != null) {
-                        IPtProxy.startLyrebird("DEBUG", false, false, null);
+                        startLyrebird();
                     }
                     startTor();
                     replyWithStatus(mIntent);
```
</details>

It's not too bad, but I did notice that there are several places where the Orbot code assumes access to global variables. For example, in CircumventionApi.kt:
```kotlin
object ServiceBuilder {
    var proxy: Proxy = Proxy(Proxy.Type.SOCKS, InetSocketAddress("127.0.0.1", IPtProxy.meekPort().toInt()))
```
This might require a significant refactor to use the above proposed API, but I'm not a skilled mobile app developer so I don't immediately know how difficult that would be. If this is too painful, we can go back to having global variables, at least for the time being.

## Missing Functionality

The main missing functionality is the Snowflake proxy callback for connected users. I left it out because it would require a patch to the Snowflake proxy library to support. This is something I would advocate for an upstream library feature.  I created an issue for it in our issue tracker: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/issues/40402

## Closing Thoughts

Let me know what you think. I'm not advocating strongly for this specific API, and would really like to hear your feedback. I am very sure that this will be much simpler to maintain than the patch files. I mostly wanted to give an idea of what can be done, on the chance that it could be more convenient for applications.

### CODE REVIEW

**Comment by cohosh** [comment]
> This might require a significant refactor to use the above proposed API, but I'm not a skilled mobile app developer so I don't immediately know how difficult that would be. If this is too painful, we can go back to having global variables, at least for the time being.

Update: This commit has the changes required for Orbot with this new IPtProxy API: https://github.com/guardianproject/orbot/compare/master...cohosh:orbot:iptproxy-refactor

I tested it to make sure the snowflake client and proxy worked, but haven't fully tested all the features (ask tor, meek, obfs4).

It didn't require too much of a refactor in the end. I really do think it is better to not rely on global variables, and the changes don't look too bad to me.

**Comment by tladesignz** [comment]
Ok, I test-drove your patches and tried using it from [`IPtProxyUI`](https://github.com/tladesignz/IPtProxyUI-ios/) and [`Orbot Apple`](https://github.com/guardianproject/orbot-apple/).

These are my thoughts:

- There needs to be constants for the transports. Undocumented magic strings are a no-go. But, that's a minor issue, should be added easily.
- There also needs to be more documentation. Every public property/function will need some text. But that's ok, I can do that.
- What's with `webtunnel` support?
- The `ipt.log` file name should be exported so it's explicit and not doubled in consuming apps.
- We definitely need the `SnowflakeProxy` callback.
- What happened with the `maxPeers` Snowflake argument?
- I couldn't compile it at first (`go.mod: missing module declaration.`), only after I started GoLand which automatically updated `go.sum`.
- I'm not overly happy about 280 + 60 + 90 lines of own code. Continuously dragging forward patches isn't cool. But the upside was, that I definitely got noticed about important changes (e.g. the recently added SQS support). Having so much logic moved to IPtProxy means, these kind of changes will go unnoticed for a long time, also, because now Snowflake and Lyrebird are normal dependencies now . That's why I asked you if you could move more logic out of main to lib back then, which you dismissed without a lot of explanation.
- I'm a little confused about the `Init`: Can I call this multiple times? Currently, my consuming lib `IPtProxyUI` configures logging on `Start`. I have to call `Init` now to reconfigure, but is that actually possible? Besides that, in general that part of the design isn't so great: There's public properties I can modify and then I have to call `Init` to actually make them do their thing. Could that be solved differently?
- I'm not at all happy with what happens with the naming in Objective-C/Swift:

```Swift
	private static let iPtProxy: IPtProxyIPtProxy? = {
		let p = IPtProxyIPtProxy(stateLocation.path)
		p?.logLevel = "WARN"
		p?.init_()

		return p
	}()
```

-> That makes me wonder if we should rebrand the lib. Have to think hard about the naming.


**But...**
besides all these points, I actually like it. The overall design is quite beautiful.

**Comment by cohosh** [comment]
> Can you provide more details to what you'd like it to look like, or link to the IPtProxyUI project?

My bad, I see the link at the top of your comment :)

**Comment by tladesignz** [comment]
> > * What's with webtunnel support?
> 
> webtunnel is already supported. So is obfs2, obfs3, and scramblesuit. All you'd need to do is call:
> 
> ```java
>  iptproxy.start("webtunnel", "socks5://localhost:8001");
> webtunnelPort = iptproxy.getPort("webtunnel");
> ```

Ah, yeah, thanks. There definitely needs to be some constants or better an enum for the transport names. (depending on what gomobile can use.)

>  > * What happened with the maxPeers Snowflake argument?
> 
> That's still configurable in the current state through Bridge line SOCKS arguments, but I could add it to the `IPtProxy` struct. I didn't add it because it's not really advantageous to use it for most configurations yet.

I see. Well, I'm not super-interested in it. If it would become relevant in the future, though, I guess it's better to have it.

> We use [semantic versioning](https://semver.org/) for both the Snowflake proxy and the Lyrebird libraries. On a minor or major version update, the new features will be visible in our [ChangeLog](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/blob/a7855d506c52b2e265678701f09de28ba1a5db22/ChangeLog). See for example, the SQS rendezvous feature in the most recent minor version update:
> 
> ```
> - Issue 26151: Implement SQS rendezvous in client and broker
> ```
> 
> I would definitely rather improve this process by improving our communication and documentation or release notes for people who use our library rather than have people rely on their build processes breaking to notice new features or changes.

Makes sense.

> As far as why we don't move the logic out of main, it's because we want to keep the library Tor-agnostic. You can see part of the reason for that by looking at the differences between this implementation and what is in the main package of Snowflake. All of the `pt.Cmethod*` functions are completely useless to you because of how you are using pluggable transports. For someone not using Tor, there would be even fewer similarities.

Also makes sense.

> That said, I am tempted to refactor out the functionality that is in snowflake.go here, which is why I put it in a separate file. This would match Lyrebird's library structure, and what I really want to do is just put it into Lyrebird for our own space-saving reasons: https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird/-/issues/40015

Oh, wow. That's an interesting development.

> I'll also note that even without moving the Snowflake SOCKS args parsing into a library, the 280 + 60 + 90 lines of code is fewer than the existing IPtProxy.go file at 450 lines of code. That's not accounting for documentation, which I'll definitely add more of, but I don't think that will add too many more lines and overall this isn't making IPtProxy larger or more complex. If (when) we factor out the snowflake.go code, it will be even fewer lines of code than the existing IPtProxy.go file, and there won't be any patch files.

Point for you. ;-)

> Init can only be called once, or it will throw an error because of some upstream library details. But that can fixed. We can definitely change how Init works overall, and move some of it into Start. I'm also not super happy with how it's structured. Can you provide more details to what you'd like it to look like, or link to the IPtProxyUI project?

I see. In that case, the values should be arguments to the `Init` call or, better yet, arguments to the constructor. (Is that possible in Go? I forgot...) Also, `Init` isn't great, because `init` is the constructor in Swift, that's why gomobile makes `init_` out of it. So getting rid of it would be super-awesome.

> > -> That makes me wonder if we should rebrand the lib. Have to think hard about the naming.
> 
> I love the idea of a rename :) Here's some inspiration: https://gitlab.torproject.org/tpo/anti-censorship/team/-/wikis/Baby-Name-Book

Haha. Very well. Nothing catches my eye, yet, though.

Anyhow, if this continues like that, we should move this whole project to the Tor Gitlab.

> I see the following immediate TODOs:
> 
> * Add in the max peers field to the IPtProxy struct
> * Fix the go.sum compilation problems
> * Add constants for transports and log file name
> * Fix Init/Start and be sure to document that fully.
> * Document every function
> * Add the SnowflakeProxy callback.
> * Open an MR for Lyrebird to add snowflake transport

- Adding the feature which triggered this whole PR: https://github.com/tladesignz/IPtProxy/issues/60

BTW: You don't necessarily need to do all this. Happy to take over most of it.
 
> Thanks for taking a look at this and giving such detailed feedback. I'll work on these updates, let me know if there's something I missed.

Well, thank you for providing all this! I'm obviously not as deeply in this stuff to come up with something similar. E.g. I never realized, that I could drop all this goptlib stuff...

**Comment by cohosh** [comment]
> BTW: You don't necessarily need to do all this. Happy to take over most of it.

Oh, go ahead :) I'll work on the upstream changes and let you know when they are ready. Here are the related merge requests:
- https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/merge_requests/424
- https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/lyrebird/-/merge_requests/63

> Adding the feature which triggered this whole PR: https://github.com/tladesignz/IPtProxy/issues/60

The way this refactor is currently written, `Start` won't return until `pt.ListenSocks` is called, which is what was causing the problems that prompted the above issue. Before, [`snowflakeclient.Start` was called in a goroutine](https://github.com/tladesignz/IPtProxy/blob/4c18db0eaf5de38c585bea56332bf00227aa35bf/IPtProxy.go/IPtProxy.go#L260), so the function could return before the SOCKS listener was ready to accept connections.

All you need to do now is just wait for `Start` to return, there's no need for a callback.

**Pull request merged**
