### PR TITLE
initial support for starting snowflake proxy and some android tweaks

### PR DESCRIPTION
**Pull request by n8fr8**
My updates .patch files include some redundant commits I think, but otherwise, the main change is the use of InitClient() InitProxy() method names instead of Main(), and some arguments to provide for obfs4

### CODE REVIEW

**Comment by n8fr8** [comment]
(unfortunately obfs4 via IPtProxy is still crashing right away on android)

**Comment by n8fr8** [comment]
These fixes make Obfs4 and Snowflake Proxy mode work

**Comment by n8fr8** [comment]
and Meek is working now as well...

**Comment by tladesignz** [comment]
Sorry, @n8fr8, there were slightly too many problems with this patch to just merge it.

To name a few:
- Method naming was seemingly done by the department of redundancy department.
- I love spaces. Spaces make stuff readable.
- I couldn't apply the Snowflake patch, it seemed broken against the latest Snowflake.
- The TOR_PT_STATE_LOCATION meddling is prone to race conditions but having it in a method signature makes it look like it doesn't have problems at all.

So I took all of your patches, modified it to my liking at released a new version 0.2.0.

However, the Snowflake stuff is still missing. Can you please send me a new pull request which is based on the latest version?

Thank you very much!

P.S.: I understand why you don't like "Main", I did neither. However, there's going to be a "Stop", so "Init" doesn't seem right, and it also clashes with Go internals. I renamed the "main" to "Start"! I hope you can live with that?

**Comment by n8fr8** [comment]
Will take a look, but all sounds good, and will work on a clean separate snowflake patch.

**Comment by tladesignz** [comment]
Ok, as spoken: I tried to understand your modified snowflake.patch. 

There was a lot of noise in it, due to patches from upstream getting applied and removed and reapplied. 

Please don't do that. The idea is, that the git submodule references a certain commit and the patch file only applies patches to make it work on mobile.
Just do a `git diff > ../snowflake.patch`, no fancy git patch listings!

I think I figured it out. Please inspect! If good, it's already released as v0.3.0!

**Comment by n8fr8** [comment]
>Please don't do that. The idea is, that the git submodule references a certain commit and the patch file only applies patches to >make it work on mobile.

Yes, it was unintentional and then I realized to far along to redeem myself what had happened.

**Pull request closed without merging**
