### PR TITLE
Add git.torproject.org/pluggable-transports/obfs4.git

### PR DESCRIPTION
**Pull request by syphyr**
Fix missing dependency and use git.torproject.org

### CODE REVIEW

**Comment by syphyr** [comment]
Forced push to fix sorting by alphabetical order

**Comment by syphyr** [comment]
This fixes https://github.com/tladesignz/IPtProxy/commit/98299c9a8d0efefd7b4088936ece54b655c3195b

**Comment by syphyr** [comment]
Fixed build.sh and bundle.sh also

**Comment by tladesignz** [comment]
Hey! Thanks for pointing this all out to me!

I fixed the breaking build for now: c9fe8c037ba0e14f9fd8b41512164ba8b52a4477

I want to first investigate though about the future of Obfs4proxy, before I switch to the Tor fork. Thanks for your patience!

**Comment by syphyr** [comment]
Thanks.  The reason why I wanted to switch to the Tor fork is that there seems to be more recent activity on that fork.
Tor/main has additional commits.

**Comment by tladesignz** [comment]
Ok, just confirmed with Tor Project, that this all makes sense:
https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/obfs4/-/issues/40010

**Comment by tladesignz** [comment]
Make sure to fetch the latest commit. Otherwise you won't get what you expect!

**Pull request merged**
